### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by porkyoot** [dankamongmen/GreenWithEnvy#6]
I just installed it and it seems awesome but sadly it crashes for me. I can briefly see the GUI but then it closes.
Here is the error in the terminal :

```
WARNING: Unknown error while executing function nvmlDeviceGetEnforcedPowerLimit
CRITICAL: Uncaught exception
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/rx/scheduler/mainloop/gtkscheduler.py", line 48, in timer_handler
    sad.disposable = self.invoke_action(cast(typing.ScheduledAction, action), state=state)
  File "/app/lib/python3.10/site-packages/rx/scheduler/scheduler.py", line 103, in invoke_action
    ret = action(self, state)
  File "/app/lib/python3.10/site-packages/rx/core/observer/scheduledobserver.py", line 63, in run
    work()
  File "/app/lib/python3.10/site-packages/rx/core/observer/scheduledobserver.py", line 28, in action
    self.observer.on_next(value)
  File "/app/lib/python3.10/site-packages/rx/core/observer/autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "/app/lib/python3.10/site-packages/gwe/presenter/main_presenter.py", line 329, in _on_status_updated
    self.main_view.refresh_status(status, self._gpu_index)
  File "/app/lib/python3.10/site-packages/gwe/view/main_view.py", line 255, in refresh_status
    self._power_limit_adjustment.set_value(limit)
TypeError: Argument 1 does not allow None as a value
```

I have a Nvidia GTX 1050 Ti Mobile with the latest Nvidia driver 535. Here is the result of `lshw -c display`

```
  *-display                 
       description: 3D controller
       product: GP107M [GeForce GTX 1050 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:152 memory:de000000-deffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:df000000-df07ffff
```

**Comment by balarooty** [comment]
Just open the file "/app/lib/python3.10/site-packages/gwe/view/main_view.py" as super user privilege and go to line 255 change the limit to either minimum or maximum

for mycase :
`self._power_limit_adjustment.set_value(maximum)`
